export * from "./user";
export * from "./patient";
export * from "./reading";
export * from "./report";
export * from "./api";
// Firestore: export only types that don't conflict with user/patient/reading/report
export type {
  Timestamp,
  DocumentReference,
  FirestoreUser,
  FirestoreUserPreferences,
  PatientAddress,
  PatientAllergies,
  EmergencyContact,
  CustomAlertRules,
  FirestorePatient,
  FirestoreReading,
  MedicalNoteType,
  FirestoreMedicalNote,
  FirestoreMedication,
  FirestoreScheduledReading,
  DocumentCategory,
  FirestorePatientDocument,
  NotificationType,
  NotificationPriority,
  FirestoreNotification,
  FirestoreUserSession,
  ReportScheduleConfig,
  FirestoreReport,
  FirestoreReportExport,
  AuditAction,
  AuditEntityType,
  FirestoreAuditLog,
  SettingCategory,
  FirestoreSetting,
  MessagePriority,
  FirestoreMessage,
  SystemHealthMetric,
  FirestoreSystemHealth,
  BackupType,
  BackupStatus,
  FirestoreBackup,
  CreateFirestoreUserDto,
  CreateFirestorePatientDto,
  CreateFirestoreReadingDto,
  CreateFirestoreMedicalNoteDto,
  CreateFirestoreMedicationDto,
  CreateFirestoreScheduledReadingDto,
  CreateFirestoreNotificationDto,
  CreateFirestoreReportDto,
  CreateFirestoreMessageDto,
  FirestoreReadingTemplate,
  CreateFirestoreReadingTemplateDto,
  FirestoreStatisticsCache,
  PatientAlertType,
  AlertPriority,
  PatientAlertMetadata,
  FirestorePatientAlert,
  CreateFirestorePatientAlertDto,
} from "./firestore";
export type { ScheduledReadingStatus } from "./firestore";
